spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
  h2.console:
    enabled: true
    path: /h2-console

flyway.datasources.default.locations: classpath:db/migration

server:
  port: 8080
